name: fypp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Locale and internacionalization
  flutter_localizations:
    sdk: flutter
  # iPhone Icons
  cupertino_icons: ^0.1.2
  # State
  mobx: ^1.2.1
  # State
  flutter_mobx: ^1.1.0
  # Injection of dependencies
  provider: ^4.0.4
  # Animation fade in
  flutter_fadein: ^1.1.1
  # Animations
  simple_animations: ^1.3.3
  # Get address by CEP
  cep_future: ^0.1.4
  # Input mask
  mask_text_input_formatter: ^1.0.6
  # Get camera and galery
  image_picker: ^0.6.7+2
  # Validators
  validators: ^2.0.0+1
  # Get image mimetype
  mime: ^0.9.6+3
  # Keep local data
  shared_preferences: ^0.5.7
  # Custom loadings
  flutter_spinkit: ^2.1.0
  # Date Textfield
  date_field: ^0.1.2
  # Dropdown list
  dropdown_formfield: ^0.1.2
  # Produtivity
  get: ^2.7.1
  # Utils
  intl: ^0.16.1
  # Pageview indicator
  dots_indicator: ^1.1.0
  # Custom combobox
  combos: ^1.2.0
  # Pagination list
  flutter_paginator: ^0.0.6
  # Custom draggableScroll
  expandable_bottom_sheet: ^0.2.1+1
  # Get multiple images of gallery
  file_picker: ^1.12.0
  # Loading network images
  cached_network_image: ^2.2.0+1
  # Credit Card
  awesome_card: ^1.1.0
  # Masks
  mask_shifter: ^0.1.0
  # Expandable card
  expandable: ^4.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Generate MobX class
  mobx_codegen: ^1.1.0
  # Generate Dart files
  build_runner: ^1.10.0
  # Initial icon
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          style: italic